import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Theranice - Location de salle pour thérapeutes",
  description: "Generated by create next app",
  icons: {
    icon: "/logo6sombre_favicon.svg",
    shortcut: "/logo6sombre_favicon.svg",
    apple: "/logo6sombre_favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${poppins.className} antialiased`}>
        <div className="min-h-screen bg-slate-50 text-slate-900">
          <SiteHeader />
          <main>{children}</main>
          <SiteFooter />
        </div>
      </body>
    </html>
  );
}
